#!/bin/bash -x
# Copyright (C) 2017 Vladimir Nadvornik
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.


# usage:
# proc_flatfield output darkframe input1.cr2 input2.cr2 ...
set -e

OUTBASE=$1

DIR=`dirname "$OUTBASE"`
mkdir -p "$DIR"
shift
DARKFRAME=$1
shift

IMGS=
for f in "$@" ; do
    if [ "${f##*.}" == fits ]; then
        df=`select_df_ff darkframe "$DARKFRAME" "$f" 0.1 fits`
        darksub --final-dark "$f" --mono --outfile "tmp_avg_$f.fits" --dark $df
        IMGS="$IMGS tmp_avg_$f.fits"
        fits=y
    else
        df=`select_df_ff darkframe "$DARKFRAME" "$f" 20 tif`
        darksub "$f" --outbayer "tmp_avg_$f.tiff" --dark $df
        IMGS="$IMGS tmp_avg_$f.tiff"
    fi
done


if [ y == "$fits" ]; then
    proc_flat3 --mono "$OUTBASE.fits" $IMGS
    darksub "$OUTBASE.fits" --mono  --outfile "$OUTBASE.tif"

#    for f in "$@" ; do
#        df=`select_df_ff darkframe "$DARKFRAME" "$f" 0.1 fits`
#        darksub --final-dark "$f" --mono --outfile "tmp_test_$f.tif" --dark $df --flat "$OUTBASE.fits" --poly-bg 2 --flat-bg --dark-bg
#        convert "tmp_test_$f.tif" -equalize "tmp_test_$f.jpg"
#        TIMGS="$TIMGS tmp_avg_$f.fits"
#    done


else
    proc_flat3 "$OUTBASE.tif" $IMGS
    cp "$OUTBASE.tif" "$OUTBASE.tiff"
    exiftool -tagsFromFile "$1" -DNGVersion=1.3.0.0 -PhotometricInterpretation='Color Filter Array' -IFD0:CFARepeatPatternDim='2 2' -IFD0:CFAPattern2='1 0 2 1' -overwrite_original_in_place "$OUTBASE.tiff"
    mv "$OUTBASE.tiff" "$OUTBASE.dng"
    exiftool -tagsFromFile "$1" -overwrite_original_in_place "$OUTBASE.tif"
fi
rm $IMGS